 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/internships", type: :request do
  
  # Internship. As you add validations to Internship, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Internship.create! valid_attributes
      get internships_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      internship = Internship.create! valid_attributes
      get internship_url(internship)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_internship_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      internship = Internship.create! valid_attributes
      get edit_internship_url(internship)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Internship" do
        expect {
          post internships_url, params: { internship: valid_attributes }
        }.to change(Internship, :count).by(1)
      end

      it "redirects to the created internship" do
        post internships_url, params: { internship: valid_attributes }
        expect(response).to redirect_to(internship_url(Internship.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Internship" do
        expect {
          post internships_url, params: { internship: invalid_attributes }
        }.to change(Internship, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post internships_url, params: { internship: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested internship" do
        internship = Internship.create! valid_attributes
        patch internship_url(internship), params: { internship: new_attributes }
        internship.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the internship" do
        internship = Internship.create! valid_attributes
        patch internship_url(internship), params: { internship: new_attributes }
        internship.reload
        expect(response).to redirect_to(internship_url(internship))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        internship = Internship.create! valid_attributes
        patch internship_url(internship), params: { internship: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested internship" do
      internship = Internship.create! valid_attributes
      expect {
        delete internship_url(internship)
      }.to change(Internship, :count).by(-1)
    end

    it "redirects to the internships list" do
      internship = Internship.create! valid_attributes
      delete internship_url(internship)
      expect(response).to redirect_to(internships_url)
    end
  end
end
