 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/internship_ops", type: :request do
  
  # InternshipOp. As you add validations to InternshipOp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      InternshipOp.create! valid_attributes
      get internship_ops_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      internship_op = InternshipOp.create! valid_attributes
      get internship_op_url(internship_op)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_internship_op_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      internship_op = InternshipOp.create! valid_attributes
      get edit_internship_op_url(internship_op)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new InternshipOp" do
        expect {
          post internship_ops_url, params: { internship_op: valid_attributes }
        }.to change(InternshipOp, :count).by(1)
      end

      it "redirects to the created internship_op" do
        post internship_ops_url, params: { internship_op: valid_attributes }
        expect(response).to redirect_to(internship_op_url(InternshipOp.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new InternshipOp" do
        expect {
          post internship_ops_url, params: { internship_op: invalid_attributes }
        }.to change(InternshipOp, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post internship_ops_url, params: { internship_op: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested internship_op" do
        internship_op = InternshipOp.create! valid_attributes
        patch internship_op_url(internship_op), params: { internship_op: new_attributes }
        internship_op.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the internship_op" do
        internship_op = InternshipOp.create! valid_attributes
        patch internship_op_url(internship_op), params: { internship_op: new_attributes }
        internship_op.reload
        expect(response).to redirect_to(internship_op_url(internship_op))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        internship_op = InternshipOp.create! valid_attributes
        patch internship_op_url(internship_op), params: { internship_op: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested internship_op" do
      internship_op = InternshipOp.create! valid_attributes
      expect {
        delete internship_op_url(internship_op)
      }.to change(InternshipOp, :count).by(-1)
    end

    it "redirects to the internship_ops list" do
      internship_op = InternshipOp.create! valid_attributes
      delete internship_op_url(internship_op)
      expect(response).to redirect_to(internship_ops_url)
    end
  end
end
