development: 
  cloud_name: "dcdjdg8gl"
  api_key: "787589888881851"
  api_secret: "iXtfxZ_qOU2IdyybmEtC0LwynzU"
  secure: true

production:
  cloud_name: "dcdjdg8gl"
  api_key: "787589888881851"
  api_secret: "iXtfxZ_qOU2IdyybmEtC0LwynzU"
  secure: truedocker run --rm -it --volume "${PWD}:/TAMU-FUSE" -e DATABASE_USER=test_app -e DATABASE_PASSWORD=test_password -p 3000:3000 dmartinez05/ruby_rails_postgresql:latest
